# Generated by Django 4.1.5 on 2023-03-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Grid', models.TextField(null=True)),
                ('Ward', models.TextField(null=True)),
                ('Block', models.TextField(null=True)),
                ('Lot', models.TextField(null=True)),
                ('Occupant', models.TextField(null=True)),
                ('Veteran', models.TextField(null=True)),
                ('Headstone', models.TextField(null=True)),
                ('Birth', models.TextField()),
                ('Death', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'graves',
            },
        ),
    ]
