# Generated by Django 4.1.5 on 2023-02-03 00:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grave',
            name='birth',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
        migrations.AlterField(
            model_name='grave',
            name='death',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
    ]
