# Generated by Django 4.1.5 on 2023-02-03 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_grave_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grave',
            name='headstone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='grave',
            name='veteran',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
