# Generated by Django 4.1.5 on 2023-02-07 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_grave_headstone_alter_grave_veteran'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grave',
            options={'verbose_name_plural': 'graves'},
        ),
        migrations.RenameField(
            model_name='grave',
            old_name='birth',
            new_name='Birth',
        ),
        migrations.RenameField(
            model_name='grave',
            old_name='headstone',
            new_name='Column',
        ),
        migrations.RenameField(
            model_name='grave',
            old_name='death',
            new_name='Death',
        ),
        migrations.RenameField(
            model_name='grave',
            old_name='first_name',
            new_name='FirstName',
        ),
        migrations.RenameField(
            model_name='grave',
            old_name='reference',
            new_name='Headstone',
        ),
        migrations.RenameField(
            model_name='grave',
            old_name='last_name',
            new_name='LastName',
        ),
        migrations.RenameField(
            model_name='grave',
            old_name='veteran',
            new_name='Reference',
        ),
        migrations.RemoveField(
            model_name='grave',
            name='middle_name',
        ),
        migrations.AddField(
            model_name='grave',
            name='Row',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='grave',
            name='Veteran',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
