# Generated by Django 4.1.5 on 2023-02-07 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_grave_options_rename_birth_grave_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grave',
            name='Birth',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='grave',
            name='Column',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='grave',
            name='Death',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='grave',
            name='FirstName',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='grave',
            name='Grid',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='grave',
            name='Headstone',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='grave',
            name='LastName',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='grave',
            name='Plot',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='grave',
            name='Reference',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='grave',
            name='Row',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='grave',
            name='Veteran',
            field=models.TextField(null=True),
        ),
    ]
