# Generated by Django 4.1.5 on 2023-02-07 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_grave_birth_alter_grave_column_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grave',
            name='Block',
        ),
        migrations.RemoveField(
            model_name='grave',
            name='Column',
        ),
        migrations.RemoveField(
            model_name='grave',
            name='Grid',
        ),
        migrations.RemoveField(
            model_name='grave',
            name='Headstone',
        ),
        migrations.RemoveField(
            model_name='grave',
            name='Lot',
        ),
        migrations.RemoveField(
            model_name='grave',
            name='Plot',
        ),
        migrations.RemoveField(
            model_name='grave',
            name='Reference',
        ),
        migrations.RemoveField(
            model_name='grave',
            name='Row',
        ),
        migrations.RemoveField(
            model_name='grave',
            name='Ward',
        ),
    ]
